services:
  db:
    image: postgres:16
    container_name: vqms_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: vqms_db
      POSTGRES_USER: vqms_user
      POSTGRES_PASSWORD: vqms_password
      TZ: Europe/Moscow
      PGTZ: Europe/Moscow
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vqms_user -d vqms_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - vqms_net

  docs:
    container_name: vqms_docs
    build:
      context: .
      dockerfile: Dockerfile.docs
    volumes:
      - .:/docs
    ports:
      - "8000:8000"
    command: serve -a 0.0.0.0:8000 -f /docs/mkdocs.yml
    profiles:
      - docs
  #docker compose --profile docs up
  #http://localhost:8000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vqms_backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: vqms_db
      DB_USER: vqms_user
      DB_PASSWORD: vqms_password
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=vqms_db;Username=vqms_user;Password=vqms_password"
    ports:
      - "8080:8080"
    networks:
      - vqms_net

volumes:
  postgres_data:

networks:
  vqms_net:
    driver: bridge