site_name: Virtual Queue Management System
site_url: https://dal1ner.github.io/virtual_queue_management_system/
docs_dir: docs
theme:
  name: material
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.indexes
    - search.highlight
    - content.code.copy

plugins:
  - search
  - mermaid2
  - swagger-ui-tag

nav:
  - Home: index.md
  - Tutorials:
    - tutorials/getting-started.md
  - How-to:
    - howto/run-locally.md
    #- howto/run-migrations.md
  - Reference:
    - reference/api/index.md
    - reference/code/backend/backend_documentation_index.md
    - reference/code/frontend/frontend_documentation_index.md
  - Explanation:
    - explanation/architecture-overview.md
    - explanation/requirements/roles.md
    - explanation/requirements/functional.md
    - explanation/requirements/non-functional.md
    - explanation/data-model/logical-data-model.md
    - explanation/development-perspective.md
    - explanation/dictionary.md
    #- explanation/diagrams/index.md
    #- explanation/adr/index.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html